### ISSUE TITLE
Mixin issue on 1.20.1

### ISSUE THREAD

**Issue by Steveplays28** [NucleoidMC/packet-tweaker#5]
[Log file](https://mclo.gs/hzVY5Sv)

Seems like Packet Tweaker is included by [Nox: Renoxed](https://github.com/qxeii/nox-renoxed).

**Comment by Patbox** [comment]
You are running 1.20.2 version of packet tweaker / nox, which is incompatible with 1.20.1

**Comment by Steveplays28** [comment]
Ah, sorry about that Patbox. Thanks for the quick response.
